name: Team approval workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'NachoAddLabel') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
