name: Team approval workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'NachoAddLabel') }}
    steps:
      - name: Label approved pull requests
        uses: abinoda/label-when-approved-action@1.0.5
        env: 
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"

    
